name: Validate with hassfest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master
